[workspace]
members = [
    "./crates/*",
    "./xtask",
    "./examples/rust/*",
    "./packages/core",
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.package]
version = "2.0.8"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/storycraft/asdf-overlay"
authors = ["storycraft <me@pancake.sh>"]
rust-version = "1.92"

[workspace.dependencies]
asdf-overlay = { version = "2.0.8", path = "./crates/overlay" }
asdf-overlay-event = { version = "2.0.8", path = "./crates/event" }
asdf-overlay-dll = { version = "2.0.8", path = "./crates/dll" }
asdf-overlay-hook = { version = "2.0.8", path = "./crates/hook" }
asdf-overlay-client = { version = "2.0.8", path = "./crates/client" }
asdf-overlay-common = { version = "2.0.8", path = "./crates/common" }
asdf-overlay-vulkan-layer = { version = "2.0.8", path = "./crates/vulkan-layer" }
asdf-overlay-window = { version = "2.0.8", path = "./crates/window" }
asdf-overlay-window-event = { version = "2.0.8", path = "./crates/window-event" }
asdf-overlay-surface-util = { version = "2.0.8", path = "./crates/surface-util" }
asdf-overlay-egui = { version = "2.0.8", path = "./crates/egui" }

tokio = "1.53.1"

[workspace.dependencies.windows]
version = "0.62.2"
