/* automatically generated by rust-bindgen 0.72.0 */

pub type gpointer = *mut ::core::ffi::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _GumInterceptor {
    _unused: [u8; 0],
}
pub type GumInterceptor = _GumInterceptor;
pub const GumReplaceReturn_GUM_REPLACE_OK: GumReplaceReturn = 0;
pub const GumReplaceReturn_GUM_REPLACE_WRONG_SIGNATURE: GumReplaceReturn = -1;
pub const GumReplaceReturn_GUM_REPLACE_ALREADY_REPLACED: GumReplaceReturn = -2;
pub const GumReplaceReturn_GUM_REPLACE_POLICY_VIOLATION: GumReplaceReturn = -3;
pub const GumReplaceReturn_GUM_REPLACE_WRONG_TYPE: GumReplaceReturn = -4;
pub type GumReplaceReturn = ::core::ffi::c_int;
unsafe extern "C" {
    pub fn gum_bindings_init();
}
unsafe extern "C" {
    pub fn gum_bindings_interceptor_obtain() -> *mut GumInterceptor;
}
unsafe extern "C" {
    pub fn gum_bindings_interceptor_replace(
        self_: *mut GumInterceptor,
        function_address: gpointer,
        replacement_function: gpointer,
        original_function: *mut gpointer,
    ) -> GumReplaceReturn;
}
unsafe extern "C" {
    pub fn gum_bindings_interceptor_begin_transaction(self_: *mut GumInterceptor);
}
unsafe extern "C" {
    pub fn gum_bindings_interceptor_end_transaction(self_: *mut GumInterceptor);
}
