/* automatically generated by rust-bindgen 0.72.0 */

pub type PVOID = *mut ::core::ffi::c_void;
pub type LONG = ::core::ffi::c_long;
unsafe extern "C" {
    #[doc = " Transaction APIs."]
    pub fn DetourTransactionBegin() -> LONG;
}
unsafe extern "C" {
    pub fn DetourTransactionAbort() -> LONG;
}
unsafe extern "C" {
    pub fn DetourTransactionCommit() -> LONG;
}
unsafe extern "C" {
    pub fn DetourTransactionCommitEx(pppFailedPointer: *mut *mut PVOID) -> LONG;
}
unsafe extern "C" {
    pub fn DetourAttach(ppPointer: *mut PVOID, pDetour: PVOID) -> LONG;
}
