[package]
name = "asdf-overlay-bindings"
description = "Asdf Overlay Bindings"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
readme = "../../README.md"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = [
    "async",
    "uniffi",
    "napi",
    "overlay",
    "overlay-event",
    "window",
    "window-event",
    "surface-util",
    "client",
]

async = []

# Binding library features
uniffi = ["dep:uniffi"]
napi = ["dep:napi-derive", "dep:napi"]

# Dependency features
overlay = ["dep:asdf-overlay", "dep:asdf-overlay-vulkan-layer", "overlay-event"]
overlay-event = ["dep:asdf-overlay-event"]
window = ["dep:asdf-overlay-window", "window-event"]
window-event = ["dep:asdf-overlay-window-event"]
surface-util = ["dep:asdf-overlay-surface-util"]
client = ["dep:asdf-overlay-client", "overlay-event", "window-event"]

[dependencies]
asdf-overlay = { workspace = true, optional = true }
asdf-overlay-vulkan-layer = { workspace = true, optional = true }
asdf-overlay-event = { workspace = true, optional = true }
asdf-overlay-window = { workspace = true, optional = true }
asdf-overlay-window-event = { workspace = true, optional = true }
asdf-overlay-surface-util = { workspace = true, optional = true }
asdf-overlay-client = { workspace = true, optional = true }
asdf-overlay-common = { workspace = true, optional = true }

uniffi = { version = "0.31.2", optional = true }
napi-derive = { version = "3.6.2", optional = true }

derive_more = { version = "2", features = ["debug", "from"] }
flume = "0.12.0"
anyhow = "1.0.97"

[dependencies.napi]
version = "3.12.0"
optional = true
features = ["napi8", "async", "error_anyhow"]
