[package]
name = "asdf-overlay-dll"
description = "Asdf Overlay Dll"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
readme = "../../README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
asdf-overlay = { workspace = true }
asdf-overlay-common = { workspace = true }
asdf-overlay-window = { workspace = true }
asdf-overlay-vulkan-layer = { workspace = true }
tokio = { workspace = true, features = ["full"] }

serde = "1.0.229"
rmp-serde = "1.3.1"
anyhow = "1.0.97"
parking_lot = { version = "0.12.3", features = ["hardware-lock-elision"] }
scopeguard = "1.2.0"
tracing-subscriber = { version = "0.3", default-features = false, features = ["parking_lot", "std"] }
arc-swap = "1.7.1"

[dependencies.windows]
workspace = true
features = [
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Diagnostics_Debug",
]

[dependencies.tracing]
version = "0.1"
features = ["max_level_trace", "release_max_level_info"]

[build-dependencies]
winres = "0.1.12"

[target.'cfg(target_env = "msvc")'.build-dependencies]
static_vcruntime = "3"

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc"]
