[package]
name = "tao-wry-overlay"
publish = false
edition.workspace = true
license.workspace = true
authors = ["storycraft <me@pancake.sh>"]

[dependencies]
asdf-overlay-client = { workspace = true, features = ["surface"] }
tokio = { workspace = true, features = ["full"] }

anyhow = "1.0.97"
rand = "0.9.3"
tao = "0.36.0"
wry = { git = 'https://github.com/jerryoh512/wry.git', branch = "feat/webview2-composition-hosting" }
scopeguard = "1.2.0"
windows-numerics = "0.3.1"

[dependencies.windows]
workspace = true
features = [
    "System",
    "Win32_Security",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D",
    "Graphics_DirectX_Direct3D11",
    "Win32_Graphics_Direct3D11",
    "Win32_System_WinRT_Direct3D11",
    "Win32_Graphics_DirectComposition",
    "Graphics_Capture",
    "UI_Composition"
]