export var Cursor;
(function (Cursor) {
    Cursor[Cursor["Default"] = 0] = "Default";
    Cursor[Cursor["Help"] = 1] = "Help";
    Cursor[Cursor["Pointer"] = 2] = "Pointer";
    Cursor[Cursor["Progress"] = 3] = "Progress";
    Cursor[Cursor["Wait"] = 4] = "Wait";
    Cursor[Cursor["Cell"] = 5] = "Cell";
    Cursor[Cursor["Crosshair"] = 6] = "Crosshair";
    Cursor[Cursor["Text"] = 7] = "Text";
    Cursor[Cursor["VerticalText"] = 8] = "VerticalText";
    Cursor[Cursor["Alias"] = 9] = "Alias";
    Cursor[Cursor["Copy"] = 10] = "Copy";
    Cursor[Cursor["Move"] = 11] = "Move";
    Cursor[Cursor["NotAllowed"] = 12] = "NotAllowed";
    Cursor[Cursor["Grab"] = 13] = "Grab";
    Cursor[Cursor["Grabbing"] = 14] = "Grabbing";
    Cursor[Cursor["ColResize"] = 15] = "ColResize";
    Cursor[Cursor["RowResize"] = 16] = "RowResize";
    Cursor[Cursor["EastWestResize"] = 17] = "EastWestResize";
    Cursor[Cursor["NorthSouthResize"] = 18] = "NorthSouthResize";
    Cursor[Cursor["NorthEastSouthWestResize"] = 19] = "NorthEastSouthWestResize";
    Cursor[Cursor["NorthWestSouthEastResize"] = 20] = "NorthWestSouthEastResize";
    Cursor[Cursor["ZoomIn"] = 21] = "ZoomIn";
    Cursor[Cursor["ZoomOut"] = 22] = "ZoomOut";
    // Windows additional cursors
    Cursor[Cursor["UpArrow"] = 23] = "UpArrow";
    Cursor[Cursor["Pin"] = 24] = "Pin";
    Cursor[Cursor["Person"] = 25] = "Person";
    Cursor[Cursor["Pen"] = 26] = "Pen";
    Cursor[Cursor["Cd"] = 27] = "Cd";
    // panning
    Cursor[Cursor["PanMiddle"] = 28] = "PanMiddle";
    Cursor[Cursor["PanMiddleHorizontal"] = 29] = "PanMiddleHorizontal";
    Cursor[Cursor["PanMiddleVertical"] = 30] = "PanMiddleVertical";
    Cursor[Cursor["PanEast"] = 31] = "PanEast";
    Cursor[Cursor["PanNorth"] = 32] = "PanNorth";
    Cursor[Cursor["PanNorthEast"] = 33] = "PanNorthEast";
    Cursor[Cursor["PanNorthWest"] = 34] = "PanNorthWest";
    Cursor[Cursor["PanSouth"] = 35] = "PanSouth";
    Cursor[Cursor["PanSouthEast"] = 36] = "PanSouthEast";
    Cursor[Cursor["PanSouthWest"] = 37] = "PanSouthWest";
    Cursor[Cursor["PanWest"] = 38] = "PanWest";
})(Cursor || (Cursor = {}));
;
