[package]
name = "asdf-overlay-hook"
description = "Asdf Overlay Hook"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
readme = "../../README.md"

[dependencies]
fn-ptr = { version = "0.9.3", features = ["max-arity-12"] }
scopeguard = "1.2.0"
thiserror = "2.0.20"
tracing = "0.1"

[build-dependencies]
anyhow = "1.0.104"
cc = "1.4.4"
frida-build = "0.17.2"
bindgen = "0.72.1"
