[package]
name = "egui-dll"
publish = false
edition.workspace = true
license.workspace = true
authors = ["storycraft <me@pancake.sh>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
asdf-overlay-egui = { workspace = true, features = ["dll"] }
pollster = { version = "1.0.1", features = ["macro"] }

tracing = "0.1.44"
