on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.rs'
  push:
    branches:
      - main
    paths:
      - '**.rs'

name: rustfmt
jobs:
  review:
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
            components: rustfmt
      - uses: actions-rust-lang/rustfmt@v1
